version: '3.8'

services:
  backend:
    image: ${DOCKER_HUB_USERNAME}/fairtrip-backend:latest
    container_name: fairtrip_backend
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
    environment:
      - MONGODB_URI=mongodb://centralized_mongo:27017
      - DATABASE_NAME=fairshare
      - ROOT_PATH=/fairtrip
    networks:
      - web_network

networks:
  web_network:
    external: true
